# version: '3.9'

services:
  app:
    build: .
    image: custom_auth:latest
    container_name: custom_auth
    volumes:
      - ./:/var/www/html
      - node:/var/www/html/node_modules
      - laravel:/var/www/html/vendor
    command: sh /var/www/html/start.prod.sh
    ports:
      - 8000:80
    depends_on:
      - mysql
    environment:
      APP_NAME: custom_auth
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://10.187.251.188

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
  mysql:
    image: mariadb:10.11.13
    container_name: custom_auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: UTC
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql:/var/lib/mysql
    # ports:
    #   - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: custom_auth_phpmyadmin
    depends_on:
      - mysql
    environment:
      UPLOAD_LIMIT: 100M
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: "/phpmyadmin/"
    ports:
      - 9000:80
    restart: unless-stopped
volumes:
  mysql:
    name: custom_auth_mysql
  node:
    name: custom_auth_node
  laravel:
    name: custom_auth_laravel